[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=1

board_build.partitions = huge_app.csv

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    bblanchon/ArduinoJson @ ^6.21.3
    esphome/AsyncTCP-esphome @ ^2.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
